---
- name: Add user
  hosts: localhost
  tasks:
   - name: add user
     user:
       name: pallavi
       shell: /bin/bash
       name: dimpi
       shell: /bin/bash
       name: shilpa
       shell: /sbin/nologin
   - name: copying file
     copy:
       src: /etc/passwd
       dest: /etc/passwd.tmp
   - name: copying a file with permissions
     copy:
       src: /etc/group
       dest: /etc/group.tmp
       owner: root
       group: root
       mode: '0644'
   - name: change file ownership, group and permissions
     file:
       path: /tmp/abc.tmp
       owner: pallavi
       group: pallavi
       state: touch
   - name: touch the file and add/remove some permissions
     file:
       path: /tmp/anu.tmp
       state: touch
       mode: u+rw,g-wx,o-rwx
  
