---
- name: Add user
  hosts: localhost
  tasks:
   - name: add user
     user:
       name: pallavi
       shell: /bin/bash
       name: dimpi
       shell: /bin/bash
       name: shilpa
       shell: /sbin/nologin
   - name: copying file
     copy:
       src: /etc/passwd
       dest: /etc/passwd.tmp
   - name: copying a file with permissions
     copy:
       src: /etc/group
       dest: /etc/group.tmp
       owner: root
       group: root
       mode: '0644'
  
